name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run gradle check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: gradle

      - name: Build
        run: ./gradlew clean check

  test_node:
    name: Build npm package
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: node/rmf-codegen
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "14"

      - name: Build npm package
        run: yarn build

      - name: Run npm package
        run: node bin/rmf-codegen.js
